/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ServiceType = { 'builderClean' : null } |
  { 'windowCleaning' : null } |
  { 'commercial' : null } |
  { 'ovenCleaning' : null } |
  { 'endOfLease' : null } |
  { 'tileAndGrout' : null } |
  { 'pressureWashing' : null } |
  { 'carpetCleaning' : null } |
  { 'officeCleaning' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getEnquiryCount' : ActorMethod<[], bigint>,
  'getFilteredSortedSubmissions' : ActorMethod<
    [[] | [ServiceType]],
    Array<ContactSubmission>
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, ServiceType, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];