/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'builderClean' : IDL.Null,
  'windowCleaning' : IDL.Null,
  'commercial' : IDL.Null,
  'ovenCleaning' : IDL.Null,
  'endOfLease' : IDL.Null,
  'tileAndGrout' : IDL.Null,
  'pressureWashing' : IDL.Null,
  'carpetCleaning' : IDL.Null,
  'officeCleaning' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFilteredSortedSubmissions' : IDL.Func(
      [IDL.Opt(ServiceType)],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'builderClean' : IDL.Null,
    'windowCleaning' : IDL.Null,
    'commercial' : IDL.Null,
    'ovenCleaning' : IDL.Null,
    'endOfLease' : IDL.Null,
    'tileAndGrout' : IDL.Null,
    'pressureWashing' : IDL.Null,
    'carpetCleaning' : IDL.Null,
    'officeCleaning' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFilteredSortedSubmissions' : IDL.Func(
        [IDL.Opt(ServiceType)],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };